<?php
$slug = (string) ($_GET['slug'] ?? '');
$stmt = $pdo->prepare(article_metrics_sql() . " WHERE a.slug=? AND a.status='published' AND p.status='approved'"); $stmt->execute([$slug]); $article = $stmt->fetch();
if (!$article) { http_response_code(404); require __DIR__ . '/404.php'; return; }
$pageTitle = $article['title'] . ' — Vi Vu Việt'; $metaDescription = $article['excerpt']; $liked=false; $userRating=0;
if ($currentUser) { $stmt=$pdo->prepare('SELECT 1 FROM article_likes WHERE article_id=? AND user_id=?'); $stmt->execute([$article['id'],$currentUser['id']]); $liked=(bool)$stmt->fetchColumn(); $stmt=$pdo->prepare('SELECT score FROM ratings WHERE article_id=? AND user_id=?'); $stmt->execute([$article['id'],$currentUser['id']]); $userRating=(int)$stmt->fetchColumn(); }
$stmt=$pdo->prepare('SELECT c.*,u.name user_name,u.role user_role,u.avatar user_avatar FROM comments c JOIN users u ON u.id=c.user_id WHERE c.article_id=? AND c.status=\'visible\' ORDER BY c.created_at DESC'); $stmt->execute([$article['id']]); $comments=$stmt->fetchAll();
$relatedStmt=$pdo->prepare(article_metrics_sql()." WHERE a.status='published' AND p.status='approved' AND a.id<>? AND (p.province_id=(SELECT province_id FROM places WHERE id=?) OR a.place_id=?) ORDER BY a.published_at DESC LIMIT 3"); $relatedStmt->execute([$article['id'],$article['place_id'],$article['place_id']]); $related=$relatedStmt->fetchAll(); $returnUrl=url('article',['slug'=>$article['slug']]);
?>
<article class="article-detail"><header class="article-header"><div class="container narrow"><div class="breadcrumbs"><a href="<?= url() ?>">Trang chủ</a><span>/</span><a href="<?= url('articles') ?>">Bài viết</a><span>/</span><a href="<?= url('place',['slug'=>$article['place_slug']]) ?>"><?= e($article['place_name']) ?></a></div><div class="article-kicker"><?= e($article['region_name']) ?> · <?= e($article['province_name']) ?></div><h1><?= e($article['title']) ?></h1><p class="article-lead"><?= e($article['excerpt']) ?></p><div class="byline"><span class="avatar"><?= e(mb_strtoupper(mb_substr($article['author_name'] ?: 'V',0,1))) ?></span><div><strong><?= e($article['author_name'] ?: 'Vi Vu Việt') ?></strong><small>Đăng ngày <?= format_date($article['published_at']) ?> · <?= max(3,(int)ceil(mb_strlen(strip_tags($article['content']))/700)) ?> phút đọc</small></div></div></div></header>
<div class="article-cover"><div class="container"><img src="<?= e(place_image($article['cover_image'])) ?>" alt="<?= e($article['title']) ?>"></div></div>
<div class="container article-layout"><aside class="article-share"><span>Chia sẻ</span><button type="button" class="copy-link" aria-label="Sao chép liên kết">⌁</button><a href="https://www.facebook.com/sharer/sharer.php?u=<?= urlencode('http://localhost.com'.$returnUrl) ?>" target="_blank" rel="noopener" aria-label="Chia sẻ Facebook">f</a></aside><div class="article-content"><div class="rich-text large rich-editor-content"><p class="dropcap"><?= e($article['excerpt']) ?></p><?= rich_content($article['content']) ?></div><div class="place-callout"><img src="<?= e(place_image($article['cover_image'])) ?>" alt=""><div><small>Địa điểm trong bài</small><h3><?= e($article['place_name']) ?></h3><p>⌖ <?= e($article['address']) ?></p><a href="<?= url('place',['slug'=>$article['place_slug']]) ?>">Xem thông tin địa điểm →</a></div></div>
<section class="engagement" id="reviews"><div><span>Bài viết này hữu ích với bạn?</span><strong>Hãy để lại một chút yêu thương</strong></div><div class="engagement-actions"><form method="post" action="<?= $returnUrl ?>"><?= csrf_field() ?><input type="hidden" name="action" value="toggle_like"><input type="hidden" name="article_id" value="<?= $article['id'] ?>"><input type="hidden" name="return_to" value="<?= e($returnUrl) ?>"><button class="like-button <?= $liked?'liked':'' ?>" type="submit">♥ <span><?= (int)$article['likes_count'] ?></span></button></form><button type="button" class="copy-link button-copy">⌁ Sao chép</button></div></section>
<section class="rating-panel"><div><h2>Đánh giá bài viết</h2><p><strong><?= $article['rating_avg'] ?: '—' ?></strong>/5 từ <?= (int)$article['ratings_count'] ?> lượt đánh giá</p></div><?php if($currentUser && $currentUser['role']==='customer'): ?><form method="post" class="star-form" action="<?= $returnUrl ?>"><?= csrf_field() ?><input type="hidden" name="action" value="rate_article"><input type="hidden" name="article_id" value="<?= $article['id'] ?>"><input type="hidden" name="return_to" value="<?= e($returnUrl) ?>"><fieldset><legend>Đánh giá của bạn</legend><?php for($i=5;$i>=1;$i--): ?><input id="star<?= $i ?>" type="radio" name="score" value="<?= $i ?>" <?= $userRating===$i?'checked':'' ?> required><label for="star<?= $i ?>" title="<?= $i ?> sao">★</label><?php endfor; ?></fieldset><button class="button button-small" type="submit">Gửi đánh giá</button></form><?php else: ?><a class="button button-outline" href="<?= url('login') ?>">Đăng nhập để đánh giá</a><?php endif; ?></section>
<section class="comments-section" id="comments"><div class="comments-title"><h2>Bình luận <span><?= count($comments) ?></span></h2><p>Cùng chia sẻ trải nghiệm một cách văn minh và hữu ích.</p></div><?php if($currentUser && $currentUser['role']==='customer'): ?><form class="comment-form" method="post" action="<?= $returnUrl ?>"><?= csrf_field() ?><input type="hidden" name="action" value="add_comment"><input type="hidden" name="article_id" value="<?= $article['id'] ?>"><input type="hidden" name="return_to" value="<?= e($returnUrl) ?>"><?= avatar_markup($currentUser) ?><div><textarea name="content" rows="4" minlength="2" maxlength="1500" placeholder="Chia sẻ cảm nhận hoặc kinh nghiệm của bạn…" required></textarea><button class="button button-small" type="submit">Đăng bình luận</button></div></form><?php else: ?><div class="login-prompt"><span>✦</span><div><strong>Tham gia cuộc trò chuyện</strong><p><a href="<?= url('login') ?>">Đăng nhập</a> hoặc <a href="<?= url('register') ?>">tạo tài khoản</a> để bình luận.</p></div></div><?php endif; ?><div class="comment-list"><?php foreach($comments as $comment): ?><article class="comment"><?= avatar_markup(['name'=>$comment['user_name'],'avatar'=>$comment['user_avatar']]) ?><div><header><strong><?= e($comment['user_name']) ?></strong><?php if($comment['user_role']==='admin'): ?><em>Quản trị viên</em><?php endif; ?><time><?= format_date($comment['created_at']) ?></time></header><p><?= nl2br(e($comment['content'])) ?></p><?php if($currentUser && (int)$comment['user_id']===(int)$currentUser['id']): ?><form method="post" action="<?= $returnUrl ?>" onsubmit="return confirm('Xóa bình luận này?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_comment"><input type="hidden" name="comment_id" value="<?= $comment['id'] ?>"><input type="hidden" name="return_to" value="<?= e($returnUrl) ?>"><button class="text-danger" type="submit">Xóa</button></form><?php endif; ?></div></article><?php endforeach; ?><?php if(!$comments): ?><p class="muted">Chưa có bình luận. Hãy bắt đầu câu chuyện đầu tiên.</p><?php endif; ?></div></section></div></div></article>
<?php if($related): ?><section class="section related-section"><div class="container"><div class="section-heading split"><h2>Có thể bạn cũng thích</h2><a class="text-link" href="<?= url('articles') ?>">Xem tất cả →</a></div><div class="article-grid"><?php foreach($related as $item): ?><article class="article-card"><a class="article-image" href="<?= url('article',['slug'=>$item['slug']]) ?>"><img src="<?= e(place_image($item['cover_image'])) ?>" alt="<?= e($item['title']) ?>"></a><div class="article-body"><div class="article-kicker"><?= e($item['province_name']) ?></div><h3><a href="<?= url('article',['slug'=>$item['slug']]) ?>"><?= e($item['title']) ?></a></h3><p><?= e($item['excerpt']) ?></p></div></article><?php endforeach; ?></div></div></section><?php endif; ?>
