<?php
$user = require_login();
if ($user['role'] !== 'customer') {
    redirect(admin_url('places/new'));
}
$editId = filter_input(INPUT_GET, 'edit', FILTER_VALIDATE_INT);
$editing = null;
if ($editId) {
    $stmt = $pdo->prepare("SELECT * FROM places WHERE id=? AND submitted_by=? AND status IN ('pending','changes_requested','rejected')");
    $stmt->execute([$editId, $user['id']]);
    $editing = $stmt->fetch();
    if (!$editing) {
        flash('error', 'Không thể chỉnh sửa địa điểm này.');
        redirect(url('profile', ['tab' => 'submissions']));
    }
}
$pageTitle = ($editing ? 'Chỉnh sửa' : 'Thêm') . ' địa danh — Vi Vu Việt';
$provinces = $pdo->query('SELECT pr.*, r.name region_name FROM provinces pr JOIN regions r ON r.id=pr.region_id ORDER BY r.id, pr.name')->fetchAll();
$categories = $pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();
?>
<section class="form-page-hero"><div class="container narrow"><div class="breadcrumbs"><a href="<?= url() ?>">Trang chủ</a><span>/</span><a href="<?= url('profile',['tab'=>'submissions']) ?>">Địa danh đã thêm</a><span>/</span><b><?= $editing ? 'Chỉnh sửa' : 'Thêm mới' ?></b></div><div class="eyebrow light"><span></span> Cùng kể chuyện quê hương</div><h1><?= $editing ? 'Chỉnh sửa địa danh' : 'Chia sẻ một địa danh mới' ?></h1><p>Thông tin rõ ràng và hình ảnh chân thật sẽ giúp admin duyệt nhanh hơn.</p></div></section>
<section class="section form-section"><div class="container form-layout"><form class="place-form" method="post" enctype="multipart/form-data" action="<?= url('submit-place', $editing ? ['edit'=>$editing['id']] : []) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="submit_place"><input type="hidden" name="return_to" value="<?= e(url('submit-place', $editing ? ['edit'=>$editing['id']] : [])) ?>"><?php if ($editing): ?><input type="hidden" name="place_id" value="<?= $editing['id'] ?>"><?php endif; ?>
    <div class="form-card"><div class="form-card-title"><span>01</span><div><h2>Thông tin cơ bản</h2><p>Giúp mọi người biết đây là nơi nào.</p></div></div><div class="form-grid"><label class="span-2">Tên địa điểm <b>*</b><input name="name" value="<?= e($editing['name'] ?? '') ?>" minlength="3" maxlength="180" placeholder="Ví dụ: Thác Bản Giốc" required></label><label>Tỉnh/thành phố <b>*</b><select name="province_id" required><option value="">Chọn tỉnh/thành</option><?php $lastRegion = ''; foreach ($provinces as $province): ?><?php if ($lastRegion !== $province['region_name']): ?><?php if ($lastRegion !== ''): ?></optgroup><?php endif; $lastRegion=$province['region_name']; ?><optgroup label="<?= e($lastRegion) ?>"><?php endif; ?><option value="<?= $province['id'] ?>" <?= ($editing['province_id'] ?? null) == $province['id'] ? 'selected' : '' ?>><?= e($province['name']) ?></option><?php endforeach; ?></optgroup></select></label><label>Loại hình <b>*</b><select name="category_id" required><option value="">Chọn loại hình</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>" <?= ($editing['category_id'] ?? null) == $category['id'] ? 'selected' : '' ?>><?= e($category['name']) ?></option><?php endforeach; ?></select></label><label class="span-2">Địa chỉ cụ thể <b>*</b><input name="address" value="<?= e($editing['address'] ?? '') ?>" minlength="5" maxlength="255" placeholder="Xã/phường, quận/huyện…" required></label><label>Giờ hoạt động<input name="opening_hours" value="<?= e($editing['opening_hours'] ?? '') ?>" maxlength="150"></label><label>Chi phí tham khảo<input name="price_info" value="<?= e($editing['price_info'] ?? '') ?>" maxlength="150"></label></div></div>
    <div class="form-card"><div class="form-card-title"><span>02</span><div><h2>Câu chuyện địa điểm</h2><p>Bài giới thiệu sẽ được gửi đến admin để duyệt.</p></div></div><div class="form-grid"><label class="span-2">Mô tả ngắn <b>*</b><textarea name="short_description" rows="3" minlength="20" maxlength="500" required><?= e($editing['short_description'] ?? '') ?></textarea><small>Từ 20 đến 500 ký tự.</small></label><label class="span-2">Bài giới thiệu chi tiết <b>*</b><textarea class="rich-editor" name="description" rows="10" minlength="80" required><?= e($editing['description'] ?? '') ?></textarea><small>Định dạng nội dung bằng CKEditor. Ít nhất 80 ký tự.</small></label></div></div>
    <div class="form-card"><div class="form-card-title"><span>03</span><div><h2>Hình ảnh</h2><p>Một tấm ảnh đẹp giúp câu chuyện sống động hơn.</p></div></div><label class="upload-zone"><input name="cover_image" type="file" accept="image/jpeg,image/png,image/webp"><span>⇧</span><strong>Chọn ảnh từ thiết bị</strong><small>JPG, PNG hoặc WebP · Tối đa 5MB</small><img class="upload-preview" alt="Xem trước ảnh"></label><div class="or-divider"><span>hoặc dùng đường dẫn ảnh</span></div><label>URL hình ảnh<input name="image_url" type="url" placeholder="https://example.com/dia-diem.jpg"></label><?php if ($editing && $editing['cover_image']): ?><div class="current-image"><span>Ảnh hiện tại</span><img src="<?= e($editing['cover_image']) ?>" alt=""></div><?php endif; ?></div>
    <div class="form-submit"><p>Gửi đồng nghĩa với việc bạn xác nhận thông tin là chân thật và đồng ý để admin biên tập trước khi xuất bản.</p><button class="button button-large" type="submit"><?= $editing ? 'Gửi lại để duyệt' : 'Gửi địa danh' ?> <span>→</span></button></div>
</form><aside class="form-guide"><div><span>✦</span><h3>Mẹo để được duyệt nhanh</h3><ul><li>Thông tin cụ thể, không sao chép.</li><li>Ảnh rõ nét và đúng địa điểm.</li><li>Thêm giờ mở cửa và chi phí nếu biết.</li><li>Không dùng nội dung quảng cáo.</li></ul></div><div class="review-process"><h3>Quy trình duyệt</h3><ol><li><b>1</b><span><strong>Bạn gửi địa danh</strong><small>Hoàn tất biểu mẫu</small></span></li><li><b>2</b><span><strong>Admin kiểm tra</strong><small>Xem nội dung và hình ảnh</small></span></li><li><b>3</b><span><strong>Địa danh lên sóng</strong><small>Bạn nhận thông báo kết quả</small></span></li></ol></div></aside></div></section>
